[workspace]
authors = ["Fernando Ferraz Ribeiro <ffribeiro@gmail.com>"]
channels = ["conda-forge"]
name = "intro_blender"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
mkdocs = ">=1.6.1,<2"
mkdocs-material = ">=9.6.22,<10"
mkdocs-jupyter = ">=0.25.1,<0.26"
pygments = ">=2.19.2,<3"

[pypi-dependencies]
mkdocs-multilang = ">=0.1.3, <0.2"
